name: Tag and Publish Go SDK

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to access full git history and tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Extract Release Tag
        id: get_tag
        run: |
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Verify Go Module availability on GOPROXY
        env:
          GOPROXY: proxy.golang.org
        run: |
          go list -m github.com/unmeshed/unmeshed-go-sdk@${{ steps.get_tag.outputs.tag_name }}
